[project]
name = "flowline"
version = "0.0.1"
description = "2.5d flowline and tools"
authors = [
    {name = "Daniel Otto", email = "drotto@uw.edu"}
]
license = {text = "LICENSE"}
requires-python = ">=3.8"
dependencies = [
    "numpy",
    "scipy",
    "matplotlib",
    "xarray",
    "tqdm",
    "pandas",
    "dill",
    "click",
    "dask[distributed]",
    "numba",
    "pyyaml",
    "seaborn",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src/"]

[project.scripts]
flowline-sweep = "cli.run_sweep:main"

[tool.pytest.ini_options]
pythonpath = "src"
